#!/usr/bin/perl
#
# filters stdin, takes out relevant frames, writes them in the format specified to the output
#
#

# little change here:
# firstarg is the subset of the frames


if($ARGV[0] eq "-goodframes") {
    # this will take in a series of frame lines and output them in a gmii
    # format, i.e. with col 0 being RX_DV, col 1 being RX_ERR, and col2 being
    # the byte; 
    while(<STDIN>){
	my $frame = $_;
	/frame (\d+) (\d+) (\d+) (\d+) (\d+)/;
	my $len = $1; 
	my $crcerr = $2;
	my $nosfs = $3; 
	my $preamblelen = $4; 
	my $phyerr = $5; 

	if ($crcerr == 0  && $nosfs == 0 && $phyerr == 0 ) {
	    print $_;
	}

	
    }
}


